import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import UiProvider from '@/lib/UiProvider';
import NavBarComponent from '@/components/NavBarComponent';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UiProvider>
          <NavBarComponent />
          <main>{children}</main>
        </UiProvider>
      </body>
    </html>
  );
}
